# Generated by Django 3.2.8 on 2021-10-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deviceToken',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='device token'),
        ),
    ]
