# Generated by Django 3.2.8 on 2021-10-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_devicetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deviceToken',
        ),
    ]
